version: "3"
services:
  homechart:
    depends_on:
      - postgres
    environment:
      HOMECHART_postgresql_hostname: postgres_homecharts
      HOMECHART_postgresql_password: aGuF962gp3Yr68rY
      HOMECHART_postgresql_username: homecharts
    image: ghcr.io/candiddev/homechart:latest
    ports:
      - "3000:3000"
    restart: always
  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    image: docker.io/postgres:16
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: {}
