version: "3"
services:
  homechart:
    depends_on:
      - postgres
    environment:
      HOMECHART_postgresql_hostname: postgres
      HOMECHART_postgresql_password: aGuF962gp3Yr68rY
      HOMECHART_postgresql_username: postgres
    image: ghcr.io/candiddev/homechart:latest
    ports:
      - "3100:3000"
    restart: unless-stopped
  postgres:
    environment:
      POSTGRES_PASSWORD: aGuF962gp3Yr68rY
    image: docker.io/postgres:16
    restart: unless-stopped
    volumes:
      - postgres-homecharts:/var/lib/postgresql/data
      
volumes:
  postgres-homecharts:
    external:
      name: postgres-homecharts

networks:
  bridge:
    external:
      name: bridge
